Raise clearer errors when configs are Missing
e.g. currently if SNOWFLAKE_PRIVATE_KEY and SNOWFLAKE_PRIVATE_KEY_PATH
are not set, the error message is:
  TypeError: no implicit conversion of nil into String